DOMAIN = "bergfex"
CONF_SKI_AREA = "ski_area"
CONF_COUNTRY = "country"
CONF_LANGUAGE = "language"
CONF_DOMAIN = "domain"
COORDINATORS = "coordinators"
BASE_URL = "https://www.bergfex.at"


# Dictionary of countries and their corresponding snow report URL paths
COUNTRIES = {
    "Österreich": "/oesterreich/schneewerte/",
    "Deutschland": "/deutschland/schneewerte/",
    "Schweiz": "/schweiz/schneewerte/",
    "Italien": "/italien/schneewerte/",
    "Frankreich": "/frankreich/schneewerte/",
    "Slowenien": "/slowenien/schneewerte/",
    "Tschechien": "/tschechien/schneewerte/",
    "Polen": "/polen/schneewerte/",
    "Slowakei": "/slowakei/schneewerte/",
}

SUPPORTED_LANGUAGES = {
    "at": {"name": "Deutsch", "domain": "https://www.bergfex.at"},
    "en": {"name": "English", "domain": "https://www.bergfex.com"},
    "fr": {"name": "Français", "domain": "https://www.bergfex.fr"},
    "it": {"name": "Italiano", "domain": "https://it.bergfex.com"},
    "es": {"name": "Español", "domain": "https://www.bergfex.es"},
    "nl": {"name": "Nederlands", "domain": "https://nl.bergfex.com"},
    "se": {"name": "Svenska", "domain": "https://se.bergfex.com"},
    "no": {"name": "Norsk", "domain": "https://no.bergfex.com"},
    "dk": {"name": "Dansk", "domain": "https://dk.bergfex.com"},
    "fi": {"name": "Suomi", "domain": "https://fi.bergfex.com"},
    "hu": {"name": "Magyar", "domain": "https://hu.bergfex.com"},
    "cz": {"name": "Český", "domain": "https://www.bergfex.cz"},
    "sk": {"name": "Slovensky", "domain": "https://www.bergfex.sk"},
    "pl": {"name": "Polski", "domain": "https://www.bergfex.pl"},
    "hr": {"name": "Hrvatski", "domain": "https://hr.bergfex.com"},
    "si": {"name": "Slovenščina", "domain": "https://www.bergfex.si"},
    "ru": {"name": "Русский", "domain": "https://ru.bergfex.com"},
    "ro": {"name": "Română", "domain": "https://ro.bergfex.com"},
}

# Keywords for parsing across different languages
KEYWORDS = {
    "at": {
        "mountain": "Berg",
        "valley": "Tal",
        "snow_depth": "Schneehöhe",
        "snow_condition": "Schneezustand",
        "last_snowfall": "Letzter Schneefall",
        "avalanche": "Lawinenwarnstufe",
        "lifts": "Offene Lifte",
        "pistes": "Offene Pisten",
        "slope_condition": "Pistenzustand",
        "today": "heute",
        "yesterday": "gestern",
        "from": "von",
        "countries": {
            "Österreich": "Österreich",
            "Deutschland": "Deutschland",
            "Schweiz": "Schweiz",
            "Italien": "Italien",
            "Frankreich": "Frankreich",
            "Slowenien": "Slowenien",
            "Tschechien": "Tschechien",
            "Polen": "Polen",
            "Slowakei": "Slowakei",
        },
        "values": {
            "keine Meldung": "keine Meldung",
            "mäßig": "mäßig",
            "gering": "gering",
            "erheblich": "erheblich",
            "groß": "groß",
            "sehr groß": "sehr groß",
            "Pulver": "Pulver",
            "Griffig": "Griffig",
            "Hart": "Hart",
            "Firn": "Firn",
            "Sulz": "Sulz",
            "Eisig": "Eisig",
        },
    },
    "en": {
        "mountain": "Mountain",
        "valley": "Valley",
        "snow_depth": "Snow report",
        "snow_condition": "Snow condition",
        "last_snowfall": "Latest snowfall Region",
        "avalanche": "Avalanche alert level",
        "lifts": "Open lifts",
        "pistes": "Open pistes",
        "slope_condition": "Piste condition",
        "today": "today",
        "yesterday": "yesterday",
        "from": "of",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Germany",
            "Schweiz": "Switzerland",
            "Italien": "Italy",
            "Frankreich": "France",
            "Slowenien": "Slovenia",
            "Tschechien": "Czech Republic",
            "Polen": "Poland",
            "Slowakei": "Slovakia",
        },
        "values": {
            "no report": "no report",
        },
    },
    "fr": {
        "mountain": "Montagne",
        "valley": "Vallée",
        "snow_depth": "Bulletin de neige",
        "snow_condition": "État de la neige",
        "last_snowfall": "Dernière chute de neige Région",
        "avalanche": "Niveau d'alerte avalanches",
        "lifts": "Remontées ouvertes",
        "pistes": "Pistes ouvertes",
        "slope_condition": "État de la piste",
        "today": "aujourd'hui",
        "yesterday": "hier",
        "from": "de",
        "countries": {
            "Österreich": "Autriche",
            "Deutschland": "Allemagne",
            "Schweiz": "Suisse",
            "Italien": "Italie",
            "Frankreich": "France",
            "Slowenien": "Slovénie",
            "Tschechien": "République Tchèque",
            "Polen": "Pologne",
            "Slowakei": "Slovaquie",
        },
        "values": {
            "pas de signalement": "unknown",
            "pas d'info": "unknown",
            "aucune information": "unknown",
        },
    },
    "it": {
        "mountain": "Montagna",
        "valley": "Valle",
        "snow_depth": "Bollettino neve",
        "snow_condition": "Condizioni neve",
        "last_snowfall": "Ultima nevicata Regione",
        "avalanche": "Livello d'allarme slavine",
        "lifts": "Impianti aperti",
        "pistes": "Piste aperte",
        "slope_condition": "Condizioni delle piste",
        "today": "oggi",
        "yesterday": "ieri",
        "from": "da",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Germania",
            "Schweiz": "Svizzera",
            "Italien": "Italia",
            "Frankreich": "Francia",
            "Slowenien": "Slovenia",
            "Tschechien": "Repubblica Ceca",
            "Polen": "Polonia",
            "Slowakei": "Slovacchia",
        },
        "values": {
            "nessuna segnalazione": "unknown",
        },
    },
    "es": {
        "mountain": "Montaña",
        "valley": "Valle",
        "snow_depth": "Parte de nieve",
        "snow_condition": "Estado de la nieve",
        "last_snowfall": "Última nevada Región",
        "avalanche": "Nivel de peligro de avalancha",
        "lifts": "Remontes mecánicos abiertos",
        "pistes": "Pistas abiertas",
        "slope_condition": "Estado de las pistas",
        "today": "hoy",
        "yesterday": "ayer",
        "from": "desde",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Alemania",
            "Schweiz": "Suiza",
            "Italien": "Italia",
            "Frankreich": "Francia",
            "Slowenien": "Eslovenia",
            "Tschechien": "República Checa",
            "Polen": "Polonia",
            "Slowakei": "Eslovaquia",
        },
        "values": {
            "sin información": "unknown",
        },
    },
    "nl": {
        "mountain": "Berg",
        "valley": "Dal",
        "snow_depth": "Sneeuwhoogte",
        "snow_condition": "Sneeuwtoestand",
        "last_snowfall": "Laatste sneeuwval",
        "avalanche": "Lawinewaarschuwingsniveau",
        "lifts": "Open liften",
        "pistes": "Open pistes",
        "slope_condition": "Pistetoestand",
        "today": "vandaag",
        "yesterday": "gisteren",
        "from": "van",
        "countries": {
            "Österreich": "Oostenrijk",
            "Deutschland": "Duitsland",
            "Schweiz": "Zwitserland",
            "Italien": "Italië",
            "Frankreich": "Frankrijk",
            "Slowenien": "Slovenië",
            "Tschechien": "Tsjechië",
            "Polen": "Polen",
            "Slowakei": "Slowakije",
        },
        "values": {
            "geen melding": "unknown",
        },
    },
    "se": {
        "mountain": "Berg",
        "valley": "Dal",
        "snow_depth": "Snölekyta",
        "snow_condition": "Snöförhållanden",
        "last_snowfall": "Senaste snöfall Region",
        "avalanche": "Varningsnivå för laviner",
        "lifts": "Öppna hissar",
        "pistes": "Öppna pister",
        "slope_condition": "Pistens skick",
        "today": "idag",
        "yesterday": "igår",
        "from": "från",
        "countries": {
            "Österreich": "Österrike",
            "Deutschland": "Tyskland",
            "Schweiz": "Schweiz",
            "Italien": "Italien",
            "Frankreich": "Frankrike",
            "Slowenien": "Slovenien",
            "Tschechien": "Tjeckien",
            "Polen": "Polen",
            "Slowakei": "Slovakien",
        },
        "values": {
            "ingen rapport": "unknown",
        },
    },
    "no": {
        "mountain": "Fjell",
        "valley": "Dal",
        "snow_depth": "Snørapport",
        "snow_condition": "Snøtilstand",
        "last_snowfall": "Siste snøfall Region",
        "avalanche": "Skredvarslingsnivå",
        "lifts": "Åpne heiser",
        "pistes": "Åpne bakker",
        "slope_condition": "Bakketilstand",
        "today": "i dag",
        "yesterday": "i går",
        "from": "av",
        "countries": {
            "Österreich": "Østerrike",
            "Deutschland": "Tyskland",
            "Schweiz": "Sveits",
            "Italien": "Italia",
            "Frankreich": "Frankrike",
            "Slowenien": "Slovenia",
            "Tschechien": "Tsjekkia",
            "Polen": "Polen",
            "Slowakei": "Slovakia",
        },
        "values": {
            "ingen melding": "unknown",
        },
    },
    "dk": {
        "mountain": "Bjerg",
        "valley": "Tal",
        "snow_depth": "Snerapport",
        "snow_condition": "Sneforhold",
        "last_snowfall": "Seneste snefald Region",
        "avalanche": "Lavine-advarselsniveau",
        "lifts": "Åbne Lifte",
        "pistes": "Åbne skråninger",
        "slope_condition": "Landingsbanens tilstand",
        "today": "i dag",
        "yesterday": "i går",
        "from": "von",
        "countries": {
            "Österreich": "Østrig",
            "Deutschland": "Tyskland",
            "Schweiz": "Schweiz",
            "Italien": "Italien",
            "Frankreich": "Frankrig",
            "Slowenien": "Slovenien",
            "Tschechien": "Tjekkiet",
            "Polen": "Polen",
            "Slowakei": "Slovakiet",
        },
        "values": {
            "ingen melding": "unknown",
        },
    },
    "fi": {
        "mountain": "Vuori",
        "valley": "Laakso",
        "snow_depth": "Lumisade-ennuste",
        "snow_condition": "Lumitilanne",
        "last_snowfall": "Viimeisin lumisade Alue",
        "avalanche": "Lumivyöryvaroitusaste",
        "lifts": "Avoimet hissit",
        "pistes": "Avoimet rinteet",
        "slope_condition": "Rinteen kunto",
        "today": "tänään",
        "yesterday": "eilen",
        "from": "pois",
        "countries": {
            "Österreich": "Itävalta",
            "Deutschland": "Saksa",
            "Schweiz": "Sveitsi",
            "Italien": "Italia",
            "Frankreich": "Ranska",
            "Slowenien": "Slovenia",
            "Tschechien": "Tšekki",
            "Polen": "Puola",
            "Slowakei": "Slovakia",
        },
        "values": {
            "ei raporttia": "unknown",
        },
    },
    "cz": {
        "mountain": "Mountain",
        "valley": "Tal",
        "snow_depth": "Sněhová předpověď",
        "snow_condition": "Stav sněhu",
        "last_snowfall": "Poslední sněžení Region",
        "avalanche": "Lavinový výstražný stupeň",
        "lifts": "Otevřené výtahy",
        "pistes": "Otevřené svahy",
        "slope_condition": "Sjezdovka",
        "today": "dnes",
        "yesterday": "včera",
        "from": "von",
        "countries": {
            "Österreich": "Rakousko",
            "Deutschland": "Německo",
            "Schweiz": "Švýcarsko",
            "Italien": "Itálie",
            "Frankreich": "Francie",
            "Slowenien": "Slovinsko",
            "Tschechien": "Česká republika",
            "Polen": "Polsko",
            "Slowakei": "Slovensko",
        },
        "values": {
            "žádná zpráva": "unknown",
        },
    },
    "sk": {
        "mountain": "Horná stanica",
        "valley": "Údolná stanica",
        "snow_depth": "Snehová správa",
        "snow_condition": "Stav snehu",
        "last_snowfall": "Posledné sneženie Región",
        "avalanche": "Stupeň lavínového nebezpečenstva",
        "lifts": "Zariadení v prevádzke",
        "pistes": "Zjazdoviek otvorených",
        "slope_condition": "Stav zjazdoviek",
        "today": "dnes",
        "yesterday": "včera",
        "from": "z",
        "countries": {
            "Österreich": "Rakúsko",
            "Deutschland": "Nemecko",
            "Schweiz": "Švajčiarsko",
            "Italien": "Taliansko",
            "Frankreich": "Francúzsko",
            "Slowenien": "Slovinsko",
            "Tschechien": "Česká republika",
            "Polen": "Poľsko",
            "Slowakei": "Slovensko",
        },
        "values": {
            "žiadna správa": "unknown",
        },
    },
    "pl": {
        "mountain": "Góra",
        "valley": "Dolina",
        "snow_depth": "Warunki śniegowe",
        "snow_condition": "Charakterystyka śniegu",
        "last_snowfall": "Ostatnie opady śniegu Region",
        "avalanche": "Stopień zagrożenia lawinowego",
        "lifts": "Otwarte wyciągi",
        "pistes": "Otwarte stoki",
        "slope_condition": "Warunki na stokach",
        "today": "dzisiaj",
        "yesterday": "wczoraj",
        "from": "z",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Niemcy",
            "Schweiz": "Szwajcaria",
            "Italien": "Włochy",
            "Frankreich": "Francja",
            "Slowenien": "Słowenia",
            "Tschechien": "Czechy",
            "Polen": "Polska",
            "Slowakei": "Słowacja",
        },
        "values": {
            "brak komunikatu": "unknown",
        },
    },
    "hr": {
        "mountain": "Planina",
        "valley": "Dolina",
        "snow_depth": "Izvješće o snijegu",
        "snow_condition": "Stanje snijega",
        "last_snowfall": "Zadnja sniježne padaline Regija",
        "avalanche": "Stupanj upozorenja na odron",
        "lifts": "Otvorene vučnice",
        "pistes": "Otvorene skijaške staze",
        "slope_condition": "Stanje skijaških staza",
        "today": "danas",
        "yesterday": "jučer",
        "from": "od",
        "countries": {
            "Österreich": "Austrija",
            "Deutschland": "Njemačka",
            "Schweiz": "Švicarska",
            "Italien": "Italija",
            "Frankreich": "Francuska",
            "Slowenien": "Slovenija",
            "Tschechien": "Češka",
            "Polen": "Poljska",
            "Slowakei": "Slovačka",
        },
        "values": {
            "nema izvješća": "unknown",
        },
    },
    "si": {
        "mountain": "Mountain",
        "valley": "Tal",
        "snow_depth": "Poročilo o snegu",
        "snow_condition": "Stanje snega",
        "last_snowfall": "Zadnje sneženje Regija",
        "avalanche": "Stopnja opozorila pred plazovi",
        "lifts": "Odprta dvigala",
        "pistes": "Odprta pobočja",
        "slope_condition": "Stanje vzletno-pristajalne steze",
        "today": "danes",
        "yesterday": "včeraj",
        "from": "von",
        "countries": {
            "Österreich": "Avstrija",
            "Deutschland": "Nemčija",
            "Schweiz": "Švica",
            "Italien": "Italija",
            "Frankreich": "Francija",
            "Slowenien": "Slovenija",
            "Tschechien": "Češka",
            "Polen": "Poljska",
            "Slowakei": "Slovaška",
        },
        "values": {
            "ni poročila": "unknown",
        },
    },
    "hu": {
        "mountain": "Hegy",
        "valley": "Völgy",
        "snow_depth": "Hójelentés",
        "snow_condition": "Hóállapot",
        "last_snowfall": "Legutóbbi hóesés Régió",
        "avalanche": "Lavinafigyelmezetési fokozat",
        "lifts": "Nyitott liftek",
        "pistes": "Nyitva lévő sípályák",
        "slope_condition": "Pályaállapot",
        "today": "ma",
        "yesterday": "tegnap",
        "from": "-tól",
        "countries": {
            "Österreich": "Ausztria",
            "Deutschland": "Németország",
            "Schweiz": "Svájc",
            "Italien": "Olaszország",
            "Frankreich": "Franciaország",
            "Slowenien": "Szlovénia",
            "Tschechien": "Csehország",
            "Polen": "Lengyelország",
            "Slowakei": "Szlovákia",
        },
        "values": {
            "nincs jelentés": "unknown",
        },
    },
    "ro": {
        "mountain": "Deal/munte",
        "valley": "Vale",
        "snow_depth": "Prognoză privind zăpada",
        "snow_condition": "Starea zăpezii",
        "last_snowfall": "Ultima cădere de zăpadă proaspătă Regiune",
        "avalanche": "Nivel de avertizare pentru avalanşe",
        "lifts": "Lifturi deschis",
        "pistes": "Piste deschise",
        "slope_condition": "Starea pistelor",
        "today": "astăzi",
        "yesterday": "ieri",
        "from": "de la",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Germania",
            "Schweiz": "Elveția",
            "Italien": "Italia",
            "Frankreich": "Franța",
            "Slowenien": "Slovenia",
            "Tschechien": "Cehia",
            "Polen": "Polonia",
            "Slowakei": "Slovacia",
        },
        "values": {
            "fără raport": "unknown",
        },
    },
    "ru": {
        "mountain": "Гора",
        "valley": "Долина",
        "snow_depth": "Сводка о состоянии снега",
        "snow_condition": "Состояние снега",
        "last_snowfall": "Последний снегопад",
        "avalanche": "Уровень предупреждения снеговых обвалов",
        "lifts": "Открытые подъемники",
        "pistes": "Открытые трассы",
        "slope_condition": "Состояние лыжни",
        "today": "сегодня",
        "yesterday": "вчера",
        "from": "с",
        "countries": {
            "Österreich": "Австрия",
            "Deutschland": "Германия",
            "Schweiz": "Швейцария",
            "Italien": "Италия",
            "Frankreich": "Франция",
            "Slowenien": "Словения",
            "Tschechien": "Чехия",
            "Polen": "Польша",
            "Slowakei": "Словакия",
        },
        "values": {
            "нет данных": "unknown",
        },
    },
    # Add other languages as needed or use a fallback mechanism
}
