DOMAIN = "bergfex"
CONF_SKI_AREA = "ski_area"
CONF_COUNTRY = "country"
CONF_LANGUAGE = "language"
CONF_DOMAIN = "domain"
CONF_TYPE = "type"
TYPE_ALPINE = "alpine"
TYPE_CROSS_COUNTRY = "cross_country"
COORDINATORS = "coordinators"
BASE_URL = "https://www.bergfex.at"
CONF_WEBHOOK_URL = "webhook_url"
CONF_UPDATE_INTERVAL = "update_interval"
DEFAULT_UPDATE_INTERVAL = 30
MIN_UPDATE_INTERVAL = 15
MAX_UPDATE_INTERVAL = 1440


# Dictionary of countries and their corresponding snow report URL paths
COUNTRIES = {
    "Österreich": "/oesterreich/schneewerte/",
    "Deutschland": "/deutschland/schneewerte/",
    "Schweiz": "/schweiz/schneewerte/",
    "Italien": "/italien/schneewerte/",
    "Frankreich": "/frankreich/schneewerte/",
    "Slowenien": "/slovenia/schneewerte/",
    "Tschechien": "/czechia/schneewerte/",
    "Polen": "/polska/schneewerte/",
    "Slowakei": "/slovakia/schneewerte/",
}

COUNTRIES_CROSS_COUNTRY = {
    "Österreich": "/oesterreich/langlaufen/loipenberichte/",
    "Deutschland": "/deutschland/langlaufen/loipenberichte/",
    "Schweiz": "/schweiz/langlaufen/loipenberichte/",
    "Italien": "/italien/langlaufen/loipenberichte/",
    "Frankreich": "/frankreich/langlaufen/loipenberichte/",
    "Slowenien": "/slovenia/langlaufen/loipenberichte/",
    "Tschechien": "/czechia/langlaufen/loipenberichte/",
    "Polen": "/polska/langlaufen/loipenberichte/",
    "Slowakei": "/slovakia/langlaufen/loipenberichte/",
}

SUPPORTED_LANGUAGES = {
    "at": {"name": "Deutsch", "domain": "https://www.bergfex.at"},
    "en": {"name": "English", "domain": "https://www.bergfex.com"},
    "fr": {"name": "Français", "domain": "https://www.bergfex.fr"},
    "it": {"name": "Italiano", "domain": "https://it.bergfex.com"},
    "es": {"name": "Español", "domain": "https://www.bergfex.es"},
    "nl": {"name": "Nederlands", "domain": "https://nl.bergfex.com"},
    "se": {"name": "Svenska", "domain": "https://se.bergfex.com"},
    "no": {"name": "Norsk", "domain": "https://no.bergfex.com"},
    "dk": {"name": "Dansk", "domain": "https://dk.bergfex.com"},
    "fi": {"name": "Suomi", "domain": "https://fi.bergfex.com"},
    "hu": {"name": "Magyar", "domain": "https://hu.bergfex.com"},
    "cz": {"name": "Český", "domain": "https://www.bergfex.cz"},
    "sk": {"name": "Slovensky", "domain": "https://www.bergfex.sk"},
    "pl": {"name": "Polski", "domain": "https://www.bergfex.pl"},
    "hr": {"name": "Hrvatski", "domain": "https://hr.bergfex.com"},
    "si": {"name": "Slovenščina", "domain": "https://www.bergfex.si"},
    "ru": {"name": "Русский", "domain": "https://ru.bergfex.com"},
    "ro": {"name": "Română", "domain": "https://ro.bergfex.com"},
}

# Keywords for parsing across different languages
KEYWORDS = {
    "at": {
        "mountain": "Berg",
        "valley": "Tal",
        "snow_depth": "Schneehöhe",
        "snow_condition": "Schneezustand",
        "last_snowfall": "Letzter Schneefall",
        "avalanche": "Lawinenwarnstufe",
        "lifts": "Offene Lifte",
        "pistes": "Offene Pisten",
        "slope_condition": "Pistenzustand",
        "prices": "Preise",
        "day_ticket": "Tageskarte",
        "today": "heute",
        "yesterday": "gestern",
        "from": "von",
        "operation": "Betrieb",
        "classical": "klassisch",
        "skating": "Skating",
        "trail_report": "Loipenbericht",
        "countries": {
            "Österreich": "Österreich",
            "Deutschland": "Deutschland",
            "Schweiz": "Schweiz",
            "Italien": "Italien",
            "Frankreich": "Frankreich",
            "Slowenien": "Slowenien",
            "Tschechien": "Tschechien",
            "Polen": "Polen",
            "Slowakei": "Slowakei",
        },
        "values": {
            "keine Meldung": "keine Meldung",
            "mäßig": "mäßig",
            "gering": "gering",
            "erheblich": "erheblich",
            "groß": "groß",
            "sehr groß": "sehr groß",
            "Pulver": "Pulver",
            "Griffig": "Griffig",
            "Hart": "Hart",
            "Firn": "Firn",
            "Sulz": "Sulz",
            "Eisig": "Eisig",
        },
        "operating_hours": "Betrieb",
        "season": "Saison",
    },
    "en": {
        "mountain": "Mountain",
        "valley": "Valley",
        "snow_depth": "Snow depth",
        "snow_condition": "Snow condition",
        "last_snowfall": "Latest snowfall Region",
        "avalanche": "Avalanche alert level",
        "lifts": "Open lifts",
        "pistes": "Open pistes",
        "slope_condition": "Piste condition",
        "prices": "Prices",
        "day_ticket": "day ticket",
        "today": "today",
        "yesterday": "yesterday",
        "from": "of",
        "operation": "Operation",
        "classical": "classical",
        "skating": "Skating",
        "trail_report": "Cross-country skiing report",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Germany",
            "Schweiz": "Switzerland",
            "Italien": "Italy",
            "Frankreich": "France",
            "Slowenien": "Slovenia",
            "Tschechien": "Czech Republic",
            "Polen": "Poland",
            "Slowakei": "Slovakia",
        },
        "values": {
            "no report": "no report",
        },
        "operating_hours": "Operating hours",
        "season": "Season",
    },
    "fr": {
        "mountain": "Montagne",
        "valley": "Vallée",
        "snow_depth": "Hauteurs de neige",
        "snow_condition": "État de la neige",
        "last_snowfall": "Dernière chute de neige Région",
        "avalanche": "Niveau d'alerte avalanches",
        "lifts": "Remontées ouvertes",
        "pistes": "Pistes ouvertes",
        "slope_condition": "État de la piste",
        "prices": "Tarifs",
        "day_ticket": "Forfait une journée",
        "today": "aujourd'hui",
        "yesterday": "hier",
        "from": "de",
        "operation": "Ouverture",
        "classical": "classique",
        "skating": "Skating",
        "trail_report": "Rapport des pistes de ski de fond",
        "countries": {
            "Österreich": "Autriche",
            "Deutschland": "Allemagne",
            "Schweiz": "Suisse",
            "Italien": "Italie",
            "Frankreich": "France",
            "Slowenien": "Slovénie",
            "Tschechien": "République Tchèque",
            "Polen": "Pologne",
            "Slowakei": "Slovaquie",
        },
        "values": {
            "pas de signalement": "unknown",
            "pas d'info": "unknown",
            "aucune information": "unknown",
        },
        "operating_hours": "Ouverture",
        "season": "Saison",
    },
    "it": {
        "mountain": "Montagna",
        "valley": "Valle",
        "snow_depth": "Altezza neve",
        "snow_condition": "Condizioni neve",
        "last_snowfall": "Ultima nevicata Regione",
        "avalanche": "Livello d'allarme slavine",
        "lifts": "Impianti aperti",
        "pistes": "Piste aperte",
        "slope_condition": "Condizioni delle piste",
        "prices": "Prezzi",
        "day_ticket": "Biglietto giornaliero",
        "today": "oggi",
        "yesterday": "ieri",
        "from": "da",
        "operation": "Orario",
        "classical": "classico",
        "skating": "Skating",
        "trail_report": "Rapporto per lo sci di fondo",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Germania",
            "Schweiz": "Svizzera",
            "Italien": "Italia",
            "Frankreich": "Francia",
            "Slowenien": "Slovenia",
            "Tschechien": "Repubblica Ceca",
            "Polen": "Polonia",
            "Slowakei": "Slovacchia",
        },
        "values": {
            "nessuna segnalazione": "unknown",
        },
        "operating_hours": "Orario",
        "season": "Stagione",
    },
    "es": {
        "mountain": "Montaña",
        "valley": "Valle",
        "snow_depth": "Espesores de nieve",
        "snow_condition": "Estado de la nieve",
        "last_snowfall": "Última caida de nieve Región",
        "avalanche": "Nivel de peligro de avalancha",
        "lifts": "Remontes mecánicos abiertos",
        "pistes": "Pistas abiertas",
        "slope_condition": "Estado de las pistas",
        "prices": "Precios",
        "day_ticket": "Billete de un día",
        "today": "hoy",
        "yesterday": "ayer",
        "from": "desde",
        "operation": "Oficina",
        "classical": "clásico",
        "skating": "Patinaje",
        "trail_report": "Informe de las pistas de esquí de fondo",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Alemania",
            "Schweiz": "Suiza",
            "Italien": "Italia",
            "Frankreich": "Francia",
            "Slowenien": "Eslovenia",
            "Tschechien": "República Checa",
            "Polen": "Polonia",
            "Slowakei": "Eslovaquia",
        },
        "values": {
            "sin información": "unknown",
        },
        "operating_hours": "Horas de funcionamiento",
        "season": "Temporada",
    },
    "nl": {
        "mountain": "Berg",
        "valley": "Dal",
        "snow_depth": "Sneeuwhoogte",
        "snow_condition": "Sneeuwtoestand",
        "last_snowfall": "Laatste sneeuwval",
        "avalanche": "Lawinewaarschuwingsniveau",
        "lifts": "Geopende liften",
        "pistes": "Open pistes",
        "slope_condition": "Pistetoestand",
        "prices": "Prijzen",
        "day_ticket": "Dagkaart",
        "today": "vandaag",
        "yesterday": "gisteren",
        "from": "van",
        "operation": "Dienst",
        "classical": "klassiek",
        "skating": "Schaatsen",
        "trail_report": "Loipenbericht",
        "countries": {
            "Österreich": "Oostenrijk",
            "Deutschland": "Duitsland",
            "Schweiz": "Zwitserland",
            "Italien": "Italië",
            "Frankreich": "Frankrijk",
            "Slowenien": "Slovenië",
            "Tschechien": "Tsjechië",
            "Polen": "Polen",
            "Slowakei": "Slowakije",
        },
        "values": {
            "geen melding": "unknown",
        },
        "operating_hours": "Bedrijfsuren",
        "season": "Seizoen",
    },
    "se": {
        "mountain": "Berg",
        "valley": "Dal",
        "snow_depth": "Snödjup",
        "snow_condition": "Snöförhållanden",
        "last_snowfall": "Sista snöfallet region",
        "avalanche": "Varningsnivå för laviner",
        "lifts": "Öppna hissar",
        "pistes": "Öppna pister",
        "slope_condition": "Pistens skick",
        "prices": "Priser",
        "day_ticket": "dagsbiljett",
        "today": "idag",
        "yesterday": "igår",
        "from": "från",
        "operation": "Drift",
        "classical": "klassisk",
        "skating": "Skridskoåkning",
        "trail_report": "Rapport om leden",
        "countries": {
            "Österreich": "Österrike",
            "Deutschland": "Tyskland",
            "Schweiz": "Schweiz",
            "Italien": "Italien",
            "Frankreich": "Frankrike",
            "Slowenien": "Slovenien",
            "Tschechien": "Tjeckien",
            "Polen": "Polen",
            "Slowakei": "Slovakien",
        },
        "values": {
            "ingen rapport": "unknown",
        },
        "operating_hours": "Drift",
        "season": "Säsong",
    },
    "no": {
        "mountain": "Fjell",
        "valley": "Dal",
        "snow_depth": "Snødybde",
        "snow_condition": "Snøtilstand",
        "last_snowfall": "Siste snøfall Region",
        "avalanche": "Skredvarslingsnivå",
        "lifts": "Åpne heiser",
        "pistes": "Åpne bakker",
        "slope_condition": "Bakketilstand",
        "prices": "Priser",
        "day_ticket": "Dagsbillett",
        "today": "i dag",
        "yesterday": "i går",
        "from": "av",
        "operation": "Yrke",
        "classical": "klassisk",
        "skating": "Skøyting",
        "trail_report": "Løyperapport",
        "countries": {
            "Österreich": "Østerrike",
            "Deutschland": "Tyskland",
            "Schweiz": "Sveits",
            "Italien": "Italia",
            "Frankreich": "Frankrike",
            "Slowenien": "Slovenia",
            "Tschechien": "Tsjekkia",
            "Polen": "Polen",
            "Slowakei": "Slovakia",
        },
        "values": {
            "ingen melding": "unknown",
        },
        "operating_hours": "Åpningstider",
        "season": "Sesong",
    },
    "dk": {
        "mountain": "Bjerg",
        "valley": "Tal",
        "snow_depth": "Snedybde",
        "snow_condition": "Sneforhold",
        "last_snowfall": "Sidste snefald region",
        "avalanche": "Lavine-advarselsniveau",
        "lifts": "Åbne Lifte",
        "pistes": "Åbne skråninger",
        "slope_condition": "Landingsbanens tilstand",
        "prices": "Priser",
        "day_ticket": "Dagsbillet",
        "today": "i dag",
        "yesterday": "i går",
        "from": "von",
        "operation": "Betjening",
        "classical": "klassisk",
        "skating": "Skøjteløb",
        "trail_report": "Loipenbericht",
        "countries": {
            "Österreich": "Østrig",
            "Deutschland": "Tyskland",
            "Schweiz": "Schweiz",
            "Italien": "Italien",
            "Frankreich": "Frankrig",
            "Slowenien": "Slovenien",
            "Tschechien": "Tjekkiet",
            "Polen": "Polen",
            "Slowakei": "Slovakiet",
        },
        "values": {
            "ingen melding": "unknown",
        },
        "operating_hours": "Driftstimer",
        "season": "Sæson",
    },
    "fi": {
        "mountain": "Vuori",
        "valley": "Laakso",
        "snow_depth": "Lumen paksuus",
        "snow_condition": "Lumitilanne",
        "last_snowfall": "Viimeisin lumisade Alue",
        "avalanche": "Lumivyöryvaroitusaste",
        "lifts": "Avoimet hissit",
        "pistes": "Avoimet rinteet",
        "slope_condition": "Rinteen kunto",
        "prices": "Hinnat",
        "day_ticket": "Päivälippu",
        "today": "tänään",
        "yesterday": "eilen",
        "from": "pois",
        "operation": "Toiminta",
        "classical": "perinteinen",
        "skating": "Luistelu",
        "trail_report": "Latutiedote",
        "countries": {
            "Österreich": "Itävalta",
            "Deutschland": "Saksa",
            "Schweiz": "Sveitsi",
            "Italien": "Italia",
            "Frankreich": "Ranska",
            "Slowenien": "Slovenia",
            "Tschechien": "Tšekki",
            "Polen": "Puola",
            "Slowakei": "Slovakia",
        },
        "values": {
            "ei raporttia": "unknown",
        },
        "operating_hours": "Toiminta-aika",
        "season": "Kausi",
    },
    "cz": {
        "mountain": "Mountain",
        "valley": "Tal",
        "snow_depth": "Hloubka sněhu",
        "snow_condition": "Stav sněhu",
        "last_snowfall": "Poslední sněžení Region",
        "avalanche": "Lavinový výstražný stupeň",
        "lifts": "Otevřené výtahy",
        "pistes": "Otevřené svahy",
        "slope_condition": "Stav vzletové a přistávací dráhy",
        "prices": "Ceny",
        "day_ticket": "denní jízdenka",
        "today": "dnes",
        "yesterday": "včera",
        "from": "von",
        "operation": "Operace",
        "classical": "classic",
        "skating": "Bruslení",
        "trail_report": "Loipenbericht",
        "countries": {
            "Österreich": "Rakousko",
            "Deutschland": "Németország",
            "Schweiz": "Svájc",
            "Italien": "Olaszország",
            "Frankreich": "Franciaország",
            "Slowenien": "Szlovénia",
            "Tschechien": "Csehország",
            "Polen": "Lengyelország",
            "Slowakei": "Szlovákia",
        },
        "values": {
            "žádná zpráva": "unknown",
        },
        "operating_hours": "Provozní doba",
        "season": "Sezóna",
    },
    "sk": {
        "mountain": "Horná stanica",
        "valley": "Údolná stanica",
        "snow_depth": "Výška snehu",
        "snow_condition": "Stav snehu",
        "last_snowfall": "Posledné sneženie Región",
        "avalanche": "Stupeň lavínového nebezpečenstva",
        "lifts": "Zariadení v prevádzke",
        "pistes": "Zjazdoviek otvorených",
        "slope_condition": "Stav zjazdoviek",
        "prices": "Ceny",
        "day_ticket": "denný lístok",
        "today": "dnes",
        "yesterday": "včera",
        "from": "z",
        "operation": "Prevádzka",
        "classical": "klasické",
        "skating": "Korčuľovanie",
        "trail_report": "Správa o bežeckých tratiach",
        "countries": {
            "Österreich": "Rakúsko",
            "Deutschland": "Nemecko",
            "Schweiz": "Švajčiarsko",
            "Italien": "Taliansko",
            "Frankreich": "Francúzsko",
            "Slowenien": "Slovinsko",
            "Tschechien": "Česká republika",
            "Polen": "Poľsko",
            "Slowakei": "Slovensko",
        },
        "values": {
            "žiadna správa": "unknown",
        },
        "operating_hours": "Prevádzkové hodiny",
        "season": "Sezóna",
    },
    "pl": {
        "mountain": "Góra",
        "valley": "Dolina",
        "snow_depth": "Grubość pokrywy śnieżnej",
        "snow_condition": "Charakterystyka śniegu",
        "last_snowfall": "Ostatnie opady śniegu Region",
        "avalanche": "Stopień zagrożenia lawinowego",
        "lifts": "Otwarte wyciągi",
        "pistes": "Otwarte stoki",
        "slope_condition": "Warunki na stokach",
        "prices": "Ceny",
        "day_ticket": "Bilet dzienny",
        "today": "dzisiaj",
        "yesterday": "wczoraj",
        "from": "z",
        "operation": "Godziny pracy w sezonie",
        "classical": "klasycznie",
        "skating": "Skating",
        "trail_report": "Raport o trasach dla narciarzy biegowych",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Niemcy",
            "Schweiz": "Szwajcaria",
            "Italien": "Włochy",
            "Frankreich": "Francja",
            "Slowenien": "Słowenia",
            "Tschechien": "Czechy",
            "Polen": "Polska",
            "Slowakei": "Słowacja",
        },
        "values": {
            "brak komunikatu": "unknown",
        },
        "operating_hours": "Godziny pracy",
        "season": "Sezon",
    },
    "hr": {
        "mountain": "Planina",
        "valley": "Dolina",
        "snow_depth": "Visina snijega",
        "snow_condition": "Stanje snijega",
        "last_snowfall": "Zadnje sniježne padaline regija",
        "avalanche": "Stupanj upozorenja na odron",
        "lifts": "Otvorene vučnice",
        "pistes": "Otvorene skijaške staze",
        "slope_condition": "Stanje skijaških staza",
        "prices": "Preise",
        "day_ticket": "Tageskarte",
        "today": "danas",
        "yesterday": "jučer",
        "from": "od",
        "operation": "Pogon",
        "classical": "klasično",
        "skating": "Skating",
        "trail_report": "Izvještaj o stazama",
        "countries": {
            "Österreich": "Austrija",
            "Deutschland": "Njemačka",
            "Schweiz": "Švicarska",
            "Italien": "Italija",
            "Frankreich": "Francuska",
            "Slowenien": "Slovenija",
            "Tschechien": "Češka",
            "Polen": "Poljska",
            "Slowakei": "Slovačka",
        },
        "values": {
            "nema izvješća": "unknown",
        },
        "operating_hours": "Betrieb",
        "season": "Saison",
    },
    "si": {
        "mountain": "Mountain",
        "valley": "Tal",
        "snow_depth": "Globina snega",
        "snow_condition": "Stanje snega",
        "last_snowfall": "Zadnje sneženje Regija",
        "avalanche": "Stopnja opozorila pred plazovi",
        "lifts": "Odprta dvigala",
        "pistes": "Odprta pobočja",
        "slope_condition": "Stanje vzletno-pristajalne steze",
        "prices": "Cene",
        "day_ticket": "dnevna vozovnica",
        "today": "danes",
        "yesterday": "včeraj",
        "from": "von",
        "operation": "Operacija",
        "classical": "classic",
        "skating": "Drsanje",
        "trail_report": "Loipenbericht",
        "countries": {
            "Österreich": "Avstrija",
            "Deutschland": "Nemčija",
            "Schweiz": "Švica",
            "Italien": "Italija",
            "Frankreich": "Francija",
            "Slowenien": "Slovenija",
            "Tschechien": "Češka",
            "Polen": "Poljska",
            "Slowakei": "Slovaška",
        },
        "values": {
            "ni poročila": "unknown",
        },
        "operating_hours": "Delovne ure",
        "season": "Sezona",
    },
    "hu": {
        "mountain": "Hegy",
        "valley": "Völgy",
        "snow_depth": "Hóvastagság",
        "snow_condition": "Hóállapot",
        "last_snowfall": "Legutóbbi hóesés Régió",
        "avalanche": "Lavinafigyelmezetési fokozat",
        "lifts": "Nyitott liftek",
        "pistes": "Nyitva lévő sípályák",
        "slope_condition": "Pályaállapot",
        "prices": "Árak",
        "day_ticket": "Napijegy",
        "today": "ma",
        "yesterday": "tegnap",
        "from": "-tól",
        "operation": "Üzem",
        "classical": "klasszikus",
        "skating": "Skating",
        "trail_report": "Sífutópálya jelentés",
        "countries": {
            "Österreich": "Ausztria",
            "Deutschland": "Németország",
            "Schweiz": "Svájc",
            "Italien": "Olaszország",
            "Frankreich": "Franciaország",
            "Slowenien": "Szlovénia",
            "Tschechien": "Csehország",
            "Polen": "Lengyelország",
            "Slowakei": "Szlovákia",
        },
        "values": {
            "nincs jelentés": "unknown",
        },
        "operating_hours": "Működési idő",
        "season": "Szezon",
    },
    "ro": {
        "mountain": "Deal/munte",
        "valley": "Vale",
        "snow_depth": "Nivelul zăpezii",
        "snow_condition": "Starea zăpezii",
        "last_snowfall": "Ultima cădere de zăpadă proaspătă Regiune",
        "avalanche": "Nivel de avertizare pentru avalanşe",
        "lifts": "Lifturi deschis",
        "pistes": "Piste deschise",
        "slope_condition": "Starea pistelor",
        "prices": "Prețuri",
        "day_ticket": "Bilet de o zi",
        "today": "astăzi",
        "yesterday": "ieri",
        "from": "de la",
        "operation": "Întreprindere/acţionare",
        "classical": "clasic",
        "skating": "Patinaj",
        "trail_report": "Raport pârtii de schi de fond",
        "countries": {
            "Österreich": "Austria",
            "Deutschland": "Germania",
            "Schweiz": "Elveția",
            "Italien": "Italia",
            "Frankreich": "Franța",
            "Slowenien": "Slovenia",
            "Tschechien": "Cehia",
            "Polen": "Polonia",
            "Slowakei": "Slovacia",
        },
        "values": {
            "fără raport": "unknown",
        },
        "operating_hours": "Ore de funcționare",
        "season": "Sezonul",
    },
    "ru": {
        "mountain": "Гора",
        "valley": "Долина",
        "snow_depth": "Высота снежного покрова",
        "snow_condition": "Состояние снега",
        "last_snowfall": "Последний снегопад",
        "avalanche": "Уровень предупреждения снеговых обвалов",
        "lifts": "Открытые подъемники",
        "pistes": "Открытые трассы",
        "slope_condition": "Состояние лыжни",
        "prices": "Цены",
        "day_ticket": "Дневной билет",
        "today": "сегодня",
        "yesterday": "вчера",
        "from": "с",
        "operation": "Работа",
        "classical": "классические",
        "skating": "Катание",
        "trail_report": "Отчёт по лыжне",
        "countries": {
            "Österreich": "Австрия",
            "Deutschland": "Германия",
            "Schweiz": "Швейцария",
            "Italien": "Италия",
            "Frankreich": "Франция",
            "Slowenien": "Словения",
            "Tschechien": "Чехия",
            "Polen": "Польша",
            "Slowakei": "Словакия",
        },
        "values": {
            "нет данных": "unknown",
        },
        "operating_hours": "Время работы",
        "season": "Сезон",
    },
}
